#!/bin/sh

# Get voyager environment, for vars and for cron
. `echo $HOME | sed "s/$LOGNAME/voyager/"`/.profile.local

# Must have filename
if [ -z "$1" ]; then
  echo $0 googlefile.tar.gz
  exit 1
fi

# Try to confirm file is .tar.gz
FILE=$1
BASE=`basename ${FILE} .tar.gz`
if [ ${FILE} = ${BASE} ]; then
  echo ${FILE} is not a .tar.gz file
  exit 1
fi

# Unpack the file
tar xvzf ${FILE}

# Should be multiple text files with names starting with $BASE
BIGFILE=${BASE}.all
cat ${BASE}*.txt > ${BIGFILE}

# If there's anything in BIGFILE, load it into Oracle
if [ -s ${BIGFILE} ]; then
  ${VGER_SCRIPT}/vger_sqlldr_load vger_report ${BIGFILE} tmp_gbs_import_2018.ctl
fi

# Clean up
rm ${BASE}*.txt ${BIGFILE}
